services:

  postgres:
    image: postgres:17
    networks:
      - db_network
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  fastapi:
    build: .
    ports:
      - "7070:8080"
    networks:
      - db_network
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always


networks:
  db_network:
    driver: bridge