"""update on delete on models

Revision ID: 9591dcbec9cc
Revises: e5a1668e1533
Create Date: 2024-12-04 15:06:27.589524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9591dcbec9cc'
down_revision: Union[str, None] = 'e5a1668e1533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_tag_tags_id_fkey', 'post_tag', type_='foreignkey')
    op.drop_constraint('post_tag_post_id_fkey', 'post_tag', type_='foreignkey')
    op.create_foreign_key(None, 'post_tag', 'post', ['post_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'post_tag', 'tag', ['tags_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.create_foreign_key('post_tag_post_id_fkey', 'post_tag', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('post_tag_tags_id_fkey', 'post_tag', 'tag', ['tags_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
