"""update comment and post tag model

Revision ID: b4e9016139d1
Revises: ea0fece117c4
Create Date: 2024-12-03 23:03:24.150483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e9016139d1'
down_revision: Union[str, None] = 'ea0fece117c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(), nullable=True))
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_post_tag_id'), 'post_tag', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_tag_id'), table_name='post_tag')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
