"""add cascade parameter on post tag

Revision ID: c33a3d0911ac
Revises: dc6ae2c2f3db
Create Date: 2024-12-03 22:55:53.323722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33a3d0911ac'
down_revision: Union[str, None] = 'dc6ae2c2f3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_tag_tags_id_fkey', 'post_tag', type_='foreignkey')
    op.drop_constraint('post_tag_post_id_fkey', 'post_tag', type_='foreignkey')
    op.create_foreign_key(None, 'post_tag', 'tag', ['tags_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tag', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.create_foreign_key('post_tag_post_id_fkey', 'post_tag', 'post', ['post_id'], ['id'])
    op.create_foreign_key('post_tag_tags_id_fkey', 'post_tag', 'tag', ['tags_id'], ['id'])
    # ### end Alembic commands ###
