name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mv env.example .env
        echo "SECRET_KEY=$(openssl rand -hex 32)" >> .env

    - name: Run tests
      run: |
        pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to Server
      env:
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem root@91.107.167.15 "bash /home/amir_projects/blog/deploy.sh"
